/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PlanetPosition = IDL.Record({
  'planet' : IDL.Text,
  'retrograde' : IDL.Bool,
  'sign' : IDL.Text,
  'degree' : IDL.Float64,
});
export const Time = IDL.Int;
export const DailyPlanetaryReport = IDL.Record({
  'insights' : IDL.Text,
  'date' : IDL.Text,
  'createdBy' : IDL.Principal,
  'timestamp' : Time,
  'positions' : IDL.Vec(PlanetPosition),
});
export const PanchangDay = IDL.Record({
  'tithi' : IDL.Text,
  'sunriseTime' : IDL.Text,
  'yoga' : IDL.Text,
  'moonsetTime' : IDL.Text,
  'sunsetTime' : IDL.Text,
  'dayNumber' : IDL.Int,
  'moonriseTime' : IDL.Text,
  'nakshatra' : IDL.Text,
  'karana' : IDL.Text,
});
export const AstroPerson = IDL.Record({
  'placeOfBirth' : IDL.Opt(IDL.Text),
  'dateOfBirth' : IDL.Text,
  'name' : IDL.Text,
  'timeOfBirth' : IDL.Opt(IDL.Text),
});
export const CompatibilityResult = IDL.Record({
  'isFavorable' : IDL.Bool,
  'score' : IDL.Float64,
  'person1' : AstroPerson,
  'person2' : AstroPerson,
  'timestamp' : Time,
  'details' : IDL.Text,
});

export const idlService = IDL.Service({
  'addDailyReport' : IDL.Func(
      [IDL.Text, IDL.Vec(PlanetPosition), IDL.Text],
      [],
      [],
    ),
  'getDailyReport' : IDL.Func([IDL.Text], [DailyPlanetaryReport], ['query']),
  'getPanchangData' : IDL.Func([IDL.Int], [PanchangDay], ['query']),
  'getRecentCompatibilities' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(CompatibilityResult)],
      ['query'],
    ),
  'saveCompatibilityResult' : IDL.Func(
      [AstroPerson, AstroPerson, IDL.Float64, IDL.Text, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PlanetPosition = IDL.Record({
    'planet' : IDL.Text,
    'retrograde' : IDL.Bool,
    'sign' : IDL.Text,
    'degree' : IDL.Float64,
  });
  const Time = IDL.Int;
  const DailyPlanetaryReport = IDL.Record({
    'insights' : IDL.Text,
    'date' : IDL.Text,
    'createdBy' : IDL.Principal,
    'timestamp' : Time,
    'positions' : IDL.Vec(PlanetPosition),
  });
  const PanchangDay = IDL.Record({
    'tithi' : IDL.Text,
    'sunriseTime' : IDL.Text,
    'yoga' : IDL.Text,
    'moonsetTime' : IDL.Text,
    'sunsetTime' : IDL.Text,
    'dayNumber' : IDL.Int,
    'moonriseTime' : IDL.Text,
    'nakshatra' : IDL.Text,
    'karana' : IDL.Text,
  });
  const AstroPerson = IDL.Record({
    'placeOfBirth' : IDL.Opt(IDL.Text),
    'dateOfBirth' : IDL.Text,
    'name' : IDL.Text,
    'timeOfBirth' : IDL.Opt(IDL.Text),
  });
  const CompatibilityResult = IDL.Record({
    'isFavorable' : IDL.Bool,
    'score' : IDL.Float64,
    'person1' : AstroPerson,
    'person2' : AstroPerson,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  
  return IDL.Service({
    'addDailyReport' : IDL.Func(
        [IDL.Text, IDL.Vec(PlanetPosition), IDL.Text],
        [],
        [],
      ),
    'getDailyReport' : IDL.Func([IDL.Text], [DailyPlanetaryReport], ['query']),
    'getPanchangData' : IDL.Func([IDL.Int], [PanchangDay], ['query']),
    'getRecentCompatibilities' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(CompatibilityResult)],
        ['query'],
      ),
    'saveCompatibilityResult' : IDL.Func(
        [AstroPerson, AstroPerson, IDL.Float64, IDL.Text, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };