/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AstroPerson {
    placeOfBirth?: string;
    dateOfBirth: string;
    name: string;
    timeOfBirth?: string;
}
export interface PlanetPosition {
    planet: string;
    retrograde: boolean;
    sign: string;
    degree: number;
}
export interface PanchangDay {
    tithi: string;
    sunriseTime: string;
    yoga: string;
    moonsetTime: string;
    sunsetTime: string;
    dayNumber: bigint;
    moonriseTime: string;
    nakshatra: string;
    karana: string;
}
export type Time = bigint;
export interface DailyPlanetaryReport {
    insights: string;
    date: string;
    createdBy: Principal;
    timestamp: Time;
    positions: Array<PlanetPosition>;
}
export interface CompatibilityResult {
    isFavorable: boolean;
    score: number;
    person1: AstroPerson;
    person2: AstroPerson;
    timestamp: Time;
    details: string;
}
export interface backendInterface {
    addDailyReport(date: string, positions: Array<PlanetPosition>, insights: string): Promise<void>;
    getDailyReport(date: string): Promise<DailyPlanetaryReport>;
    getPanchangData(dayNumber: bigint): Promise<PanchangDay>;
    getRecentCompatibilities(limit: bigint): Promise<Array<CompatibilityResult>>;
    saveCompatibilityResult(person1: AstroPerson, person2: AstroPerson, score: number, details: string, isFavorable: boolean): Promise<void>;
}
import type { AstroPerson as _AstroPerson, CompatibilityResult as _CompatibilityResult, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDailyReport(arg0: string, arg1: Array<PlanetPosition>, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyReport(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyReport(arg0, arg1, arg2);
            return result;
        }
    }
    async getDailyReport(arg0: string): Promise<DailyPlanetaryReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyReport(arg0);
            return result;
        }
    }
    async getPanchangData(arg0: bigint): Promise<PanchangDay> {
        if (this.processError) {
            try {
                const result = await this.actor.getPanchangData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPanchangData(arg0);
            return result;
        }
    }
    async getRecentCompatibilities(arg0: bigint): Promise<Array<CompatibilityResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentCompatibilities(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentCompatibilities(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCompatibilityResult(arg0: AstroPerson, arg1: AstroPerson, arg2: number, arg3: string, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCompatibilityResult(to_candid_AstroPerson_n7(this._uploadFile, this._downloadFile, arg0), to_candid_AstroPerson_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCompatibilityResult(to_candid_AstroPerson_n7(this._uploadFile, this._downloadFile, arg0), to_candid_AstroPerson_n7(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_AstroPerson_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AstroPerson): AstroPerson {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_CompatibilityResult_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompatibilityResult): CompatibilityResult {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isFavorable: boolean;
    score: number;
    person1: _AstroPerson;
    person2: _AstroPerson;
    timestamp: _Time;
    details: string;
}): {
    isFavorable: boolean;
    score: number;
    person1: AstroPerson;
    person2: AstroPerson;
    timestamp: Time;
    details: string;
} {
    return {
        isFavorable: value.isFavorable,
        score: value.score,
        person1: from_candid_AstroPerson_n4(_uploadFile, _downloadFile, value.person1),
        person2: from_candid_AstroPerson_n4(_uploadFile, _downloadFile, value.person2),
        timestamp: value.timestamp,
        details: value.details
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfBirth: [] | [string];
    dateOfBirth: string;
    name: string;
    timeOfBirth: [] | [string];
}): {
    placeOfBirth?: string;
    dateOfBirth: string;
    name: string;
    timeOfBirth?: string;
} {
    return {
        placeOfBirth: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.placeOfBirth)),
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        timeOfBirth: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.timeOfBirth))
    };
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompatibilityResult>): Array<CompatibilityResult> {
    return value.map((x)=>from_candid_CompatibilityResult_n2(_uploadFile, _downloadFile, x));
}
function to_candid_AstroPerson_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AstroPerson): _AstroPerson {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placeOfBirth?: string;
    dateOfBirth: string;
    name: string;
    timeOfBirth?: string;
}): {
    placeOfBirth: [] | [string];
    dateOfBirth: string;
    name: string;
    timeOfBirth: [] | [string];
} {
    return {
        placeOfBirth: value.placeOfBirth ? candid_some(value.placeOfBirth) : candid_none(),
        dateOfBirth: value.dateOfBirth,
        name: value.name,
        timeOfBirth: value.timeOfBirth ? candid_some(value.timeOfBirth) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
